/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/sasamba.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-1.62, 1.16, -5.39]} scale={0.69}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Logo_prizmarine_(1)"].geometry}
          material={nodes["Logo_prizmarine_(1)"].material}
          position={[-0.23, 0.5, -0.04]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[3.17, 3.17, 3.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lighting_logo.geometry}
          material={nodes.lighting_logo.material}
          position={[-0.23, 0.5, -0.04]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[3.17, 3.17, 3.17]}
        />
      </group>
      <group position={[-4.21, 1.13, -1.43]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lamp_01.geometry}
          material={nodes.lamp_01.material}
          position={[0.08, 0.26, 0.18]}
          rotation={[2.67, -0.38, 1.39]}
          scale={[1.16, 1.16, 1.16]}
        />
      </group>
      <group position={[-4.21, 1.13, -4.88]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["lamp_002_(1)"].geometry}
          material={nodes["lamp_002_(1)"].material}
          position={[0.08, 0.26, 0.18]}
          rotation={[2.67, -0.38, 1.39]}
          scale={[1.16, 1.16, 1.16]}
        />
      </group>
      <group position={[-1.3, 1.13, -3.1]} rotation={[0, -1.56, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["lamp_004_(1)"].geometry}
          material={nodes["lamp_004_(1)"].material}
          position={[0.08, 0.26, 0.18]}
          rotation={[2.67, -0.38, 1.39]}
          scale={[1.16, 1.16, 1.16]}
        />
      </group>
      <group position={[-3.25, 1.13, 1.89]} rotation={[Math.PI, -1.2, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["lamp_003_(1)"].geometry}
          material={nodes["lamp_003_(1)"].material}
          position={[0.08, 0.26, 0.18]}
          rotation={[2.67, -0.38, 1.39]}
          scale={[1.16, 1.16, 1.16]}
        />
      </group>
      <primitive object={nodes.mixamorigHips} />
      <primitive object={nodes.mixamorigHips001} />
      <primitive object={nodes.mixamorigHips002} />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls.geometry}
        material={nodes.walls.material}
        position={[0.38, 0, -1.1]}
        scale={[2.49, 1.55, 2.49]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flower.geometry}
        material={nodes.flower.material}
        position={[5.02, 0.49, -0.65]}
        rotation={[0, -0.64, 0]}
        scale={[93.09, 93.09, 93.09]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carpet.geometry}
        material={nodes.carpet.material}
        position={[3.64, 0, 0.86]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.interactive_whiteboard.geometry}
        material={nodes.interactive_whiteboard.material}
        position={[3.81, 1.12, -5.44]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass_partition.geometry}
        material={nodes.glass_partition.material}
        position={[3.85, 0, -0.96]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.columm_konstruct.geometry}
        material={nodes.columm_konstruct.material}
        position={[1.67, 0, -5.13]}
      />
      <group
        position={[0.59, 1.71, -5.17]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder10_1.geometry}
          material={nodes.Doc_folder10_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder10_2.geometry}
          material={nodes.Doc_folder10_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder10_3.geometry}
          material={nodes.Doc_folder10_3.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.working_table04.geometry}
        material={nodes.working_table04.material}
        position={[-3.67, 0.75, -5.04]}
        rotation={[0, 0, -Math.PI]}
        scale={[1, -1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.working_table01.geometry}
        material={nodes.working_table01.material}
        position={[-1.83, 0.75, -3.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.working_table02.geometry}
        material={nodes.working_table02.material}
        position={[-4.17, 0.75, -1.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.working_table03.geometry}
        material={nodes.working_table03.material}
        position={[-3.67, 0.75, 1.85]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgrounf.geometry}
        material={nodes.backgrounf.material}
        position={[5.76, 1.38, -2.45]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <group
        position={[0.67, 1.71, -5.17]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder07_1.geometry}
          material={nodes.Doc_folder07_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder07_2.geometry}
          material={nodes.Doc_folder07_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder07_3.geometry}
          material={nodes.Doc_folder07_3.material}
        />
      </group>
      <group
        position={[0.74, 1.71, -5.17]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder06_1.geometry}
          material={nodes.Doc_folder06_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder06_2.geometry}
          material={nodes.Doc_folder06_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder06_3.geometry}
          material={nodes.Doc_folder06_3.material}
        />
      </group>
      <group
        position={[0.09, 1.71, -5.18]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder09_1.geometry}
          material={nodes.Doc_folder09_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder09_2.geometry}
          material={nodes.Doc_folder09_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder09_3.geometry}
          material={nodes.Doc_folder09_3.material}
        />
      </group>
      <group
        position={[-0.4, 1.71, -5.18]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder09_1.geometry}
          material={nodes.Doc_folder09_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder09_2.geometry}
          material={nodes.Doc_folder09_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder09_3.geometry}
          material={nodes.Doc_folder09_3.material}
        />
      </group>
      <group
        position={[-0.4, 2.07, -5.18]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder09_1.geometry}
          material={nodes.Doc_folder09_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder09_2.geometry}
          material={nodes.Doc_folder09_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder09_3.geometry}
          material={nodes.Doc_folder09_3.material}
        />
      </group>
      <group
        position={[-0.88, 2.07, -5.18]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder09_1.geometry}
          material={nodes.Doc_folder09_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder09_2.geometry}
          material={nodes.Doc_folder09_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder09_3.geometry}
          material={nodes.Doc_folder09_3.material}
        />
      </group>
      <group
        position={[0.17, 1.71, -5.17]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder08_1.geometry}
          material={nodes.Doc_folder08_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder08_2.geometry}
          material={nodes.Doc_folder08_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder08_3.geometry}
          material={nodes.Doc_folder08_3.material}
        />
      </group>
      <group
        position={[-0.33, 1.71, -5.17]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder08_1.geometry}
          material={nodes.Doc_folder08_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder08_2.geometry}
          material={nodes.Doc_folder08_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder08_3.geometry}
          material={nodes.Doc_folder08_3.material}
        />
      </group>
      <group
        position={[-0.33, 2.07, -5.17]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder08_1.geometry}
          material={nodes.Doc_folder08_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder08_2.geometry}
          material={nodes.Doc_folder08_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder08_3.geometry}
          material={nodes.Doc_folder08_3.material}
        />
      </group>
      <group
        position={[-0.8, 2.07, -5.17]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder08_1.geometry}
          material={nodes.Doc_folder08_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder08_2.geometry}
          material={nodes.Doc_folder08_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder08_3.geometry}
          material={nodes.Doc_folder08_3.material}
        />
      </group>
      <group
        position={[0.25, 1.71, -5.18]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder05_1.geometry}
          material={nodes.Doc_folder05_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder05_2.geometry}
          material={nodes.Doc_folder05_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder05_3.geometry}
          material={nodes.Doc_folder05_3.material}
        />
      </group>
      <group
        position={[-0.25, 1.71, -5.18]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder05_1.geometry}
          material={nodes.Doc_folder05_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder05_2.geometry}
          material={nodes.Doc_folder05_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder05_3.geometry}
          material={nodes.Doc_folder05_3.material}
        />
      </group>
      <group
        position={[-0.25, 2.07, -5.18]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder05_1.geometry}
          material={nodes.Doc_folder05_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder05_2.geometry}
          material={nodes.Doc_folder05_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder05_3.geometry}
          material={nodes.Doc_folder05_3.material}
        />
      </group>
      <group
        position={[-0.72, 2.07, -5.18]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder05_1.geometry}
          material={nodes.Doc_folder05_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder05_2.geometry}
          material={nodes.Doc_folder05_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder05_3.geometry}
          material={nodes.Doc_folder05_3.material}
        />
      </group>
      <group
        position={[0.32, 1.71, -5.17]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder02_1.geometry}
          material={nodes.Doc_folder02_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder02_2.geometry}
          material={nodes.Doc_folder02_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder02_3.geometry}
          material={nodes.Doc_folder02_3.material}
        />
      </group>
      <group
        position={[-0.17, 1.71, -5.17]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder02_1.geometry}
          material={nodes.Doc_folder02_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder02_2.geometry}
          material={nodes.Doc_folder02_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder02_3.geometry}
          material={nodes.Doc_folder02_3.material}
        />
      </group>
      <group
        position={[-0.17, 2.07, -5.17]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder02_1.geometry}
          material={nodes.Doc_folder02_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder02_2.geometry}
          material={nodes.Doc_folder02_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder02_3.geometry}
          material={nodes.Doc_folder02_3.material}
        />
      </group>
      <group
        position={[-0.64, 2.07, -5.17]}
        rotation={[Math.PI, -1.47, Math.PI]}
        scale={36.13}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder02_1.geometry}
          material={nodes.Doc_folder02_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder02_2.geometry}
          material={nodes.Doc_folder02_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doc_folder02_3.geometry}
          material={nodes.Doc_folder02_3.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.columm.geometry}
        material={nodes.columm.material}
        position={[2.02, 0, -0.84]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.columm_light.geometry}
        material={nodes.columm_light.material}
        position={[1.74, 1.89, -0.95]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fridge.geometry}
        material={materials["Red-Metall"]}
        position={[5.03, 0.62, 1.33]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={283.14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pen01.geometry}
        material={nodes.pen01.material}
        position={[3.54, 0.79, -3.01]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={79.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pen002.geometry}
        material={nodes.pen002.material}
        position={[3.54, 0.79, -2.04]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={79.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pen003.geometry}
        material={nodes.pen003.material}
        position={[4.17, 0.79, -3.01]}
        scale={79.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pen004.geometry}
        material={nodes.pen004.material}
        position={[4.17, 0.79, -2.04]}
        scale={79.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.working_chair01.geometry}
        material={nodes.working_chair01.material}
        position={[-1.09, 0, -0.96]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[1.34, -1.34, 1.34]}
      />
      <group
        position={[5.07, 0, 1.99]}
        rotation={[-Math.PI, -1.57, 0]}
        scale={[176.88, -176.88, 176.88]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cooler_1.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cooler_2.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cooler_3.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cooler_4.geometry}
          material={nodes.cooler_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cooler_5.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cooler_6.geometry}
          material={nodes.cooler_6.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cooler_7.geometry}
          material={nodes.cooler_7.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cooler_8.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group
        position={[4.98, 0.64, 0.86]}
        rotation={[0, -1.57, 0]}
        scale={430.55}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.coffe_machine_1.geometry}
          material={nodes.coffe_machine_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.coffe_machine_2.geometry}
          material={materials["Material.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.coffe_machine_3.geometry}
          material={nodes.coffe_machine_3.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall_desk.geometry}
        material={nodes.wall_desk.material}
        position={[-3.28, 1.55, -5.36]}
        scale={376.4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.klava.geometry}
        material={nodes.klava.material}
        position={[-0.99, 0.77, -1.2]}
        rotation={[0.57, -1.36, 0.56]}
        scale={[10, 10, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.klava001.geometry}
        material={nodes.klava001.material}
        position={[-4.08, 0.77, -0.96]}
        rotation={[2.23, 1.43, -2.24]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.klava002.geometry}
        material={nodes.klava002.material}
        position={[-4.01, 0.77, -4.58]}
        rotation={[0.26, 1.12, -0.23]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.klava003.geometry}
        material={nodes.klava003.material}
        position={[-2.06, 0.77, -3.16]}
        rotation={[0.11, 0.17, -0.02]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computer_tower_01.geometry}
        material={nodes.computer_tower_01.material}
        position={[-4.2, 0, 0.91]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computer_tower_04.geometry}
        material={nodes.computer_tower_04.material}
        position={[-1.24, 0, -3.36]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computer_tower_05.geometry}
        material={nodes.computer_tower_05.material}
        position={[-2.92, 0, -5.02]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computer_tower_02.geometry}
        material={nodes.computer_tower_02.material}
        position={[-4.09, 0, -0.66]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computer_tower_03.geometry}
        material={nodes.computer_tower_03.material}
        position={[-0.86, 0, -1.43]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.laptop.geometry}
        material={nodes.laptop.material}
        position={[-1.49, 0.78, -3.41]}
        rotation={[0, -0.2, 0]}
        scale={1.78}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mouse003.geometry}
        material={nodes.mouse003.material}
        position={[-1.52, 0.77, -3.15]}
        scale={[27.91, 27.91, 27.91]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mouse002.geometry}
        material={nodes.mouse002.material}
        position={[-3.52, 0.77, -4.9]}
        rotation={[0, Math.PI / 9, 0]}
        scale={[27.91, 27.91, 27.91]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mouse001.geometry}
        material={nodes.mouse001.material}
        position={[-4.02, 0.77, -1.5]}
        rotation={[0, 1.48, 0]}
        scale={[27.91, 27.91, 27.91]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mouse.geometry}
        material={nodes.mouse.material}
        position={[-1, 0.77, -0.66]}
        rotation={[0, -1.57, 0]}
        scale={[27.91, 27.91, 27.91]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen07.geometry}
        material={nodes.screen07.material}
        position={[-3.89, 0.97, -5.1]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor.geometry}
        material={nodes.floor.material}
        position={[0.38, 0, -1.1]}
        scale={[2.49, 1.55, 2.49]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen06.geometry}
        material={nodes.screen06.material}
        position={[-4.29, 0.97, -4.58]}
        rotation={[0, 1.31, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen02.geometry}
        material={nodes.screen02.material}
        position={[-4.4, 0.97, 1.5]}
        rotation={[-Math.PI, 1.25, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen05.geometry}
        material={nodes.screen05.material}
        position={[-3.97, 0.97, 2]}
        rotation={[-Math.PI, 0.46, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen03.geometry}
        material={nodes.screen03.material}
        position={[-0.68, 0.97, -1.16]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen04.geometry}
        material={nodes.screen04.material}
        position={[-2.11, 0.97, -3.48]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen01.geometry}
        material={nodes.screen01.material}
        position={[-4.35, 0.97, -1.05]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.working_chair02.geometry}
        material={nodes.working_chair02.material}
        position={[-3.66, 0, -1.04]}
        rotation={[0, -1.48, Math.PI]}
        scale={[1.34, -1.34, 1.34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.working_chair03.geometry}
        material={nodes.working_chair03.material}
        position={[-1.94, 0, -2.27]}
        rotation={[-Math.PI, -0.17, 0]}
        scale={[1.34, -1.34, 1.34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.working_chair04.geometry}
        material={nodes.working_chair04.material}
        position={[-3.75, 0, -4.4]}
        rotation={[0, -1.48, Math.PI]}
        scale={[1.34, -1.34, 1.34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.working_chair05.geometry}
        material={nodes.working_chair05.material}
        position={[-3.42, 0, 1.25]}
        rotation={[0, -1.13, Math.PI]}
        scale={[1.34, -1.34, 1.34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kitchen_cupboard.geometry}
        material={nodes.kitchen_cupboard.material}
        position={[5.31, 1.52, 0.4]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <group position={[1.91, 0, -0.45]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trash_bucket_1.geometry}
          material={materials["Material #901"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trash_bucket_2.geometry}
          material={materials["Material #900"]}
        />
      </group>
      <group position={[5.02, 0, 0.74]} rotation={[0, -1.57, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chest_1.geometry}
          material={nodes.chest_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chest_2.geometry}
          material={materials["Material #438"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chest_3.geometry}
          material={materials["Material #437"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sofa.geometry}
        material={nodes.Sofa.material}
        position={[3.64, 0.32, -0.55]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine01.geometry}
        material={nodes.magazine01.material}
        position={[1.09, 0.94, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine02.geometry}
        material={nodes.magazine02.material}
        position={[1.08, 0.94, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine03.geometry}
        material={nodes.magazine03.material}
        position={[1.07, 0.94, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine04.geometry}
        material={nodes.magazine04.material}
        position={[1.06, 0.94, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine05.geometry}
        material={nodes.magazine05.material}
        position={[1.06, 0.94, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine07.geometry}
        material={nodes.magazine07.material}
        position={[1.04, 0.94, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine14.geometry}
        material={nodes.magazine14.material}
        position={[1.02, 0.94, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine06.geometry}
        material={nodes.magazine06.material}
        position={[1.05, 0.95, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine08.geometry}
        material={nodes.magazine08.material}
        position={[1.03, 0.95, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine15.geometry}
        material={nodes.magazine15.material}
        position={[1.01, 0.95, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine09.geometry}
        material={nodes.magazine09.material}
        position={[1.17, 0.13, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine10.geometry}
        material={nodes.magazine10.material}
        position={[1.17, 0.12, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine11.geometry}
        material={nodes.magazine11.material}
        position={[1.17, 0.11, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine12.geometry}
        material={nodes.magazine12.material}
        position={[1.18, 0.11, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine13.geometry}
        material={nodes.magazine13.material}
        position={[1, 0.94, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine16.geometry}
        material={nodes.magazine16.material}
        position={[0.99, 0.95, -5.24]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bif_wardrobe.geometry}
        material={nodes.bif_wardrobe.material}
        position={[0.77, 1, -5.14]}
        scale={0.86}
      />
      <group
        position={[1.34, 1.54, -5.24]}
        rotation={[0, -0.7, 0]}
        scale={[6.97, 6.97, 6.97]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lego_spider_man_1.geometry}
          material={materials["Untitled Model_Decoration_3626d577"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lego_spider_man_2.geometry}
          material={materials["Untitled Model_Decoration_3814d469"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lego_spider_man_3.geometry}
          material={materials["Untitled Model_Decoration_3818d469"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lego_spider_man_4.geometry}
          material={materials["Untitled Model_Color_21"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lego_spider_man_5.geometry}
          material={materials["Untitled Model_Decoration_3819d469"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lego_spider_man_6.geometry}
          material={materials["Untitled Model_Color_140"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lego_spider_man_7.geometry}
          material={materials["Untitled Model_Decoration_20932d136"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lego_spider_man_8.geometry}
          material={materials["Untitled Model_Decoration_20926d136"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.partition.geometry}
        material={nodes.partition.material}
        position={[1.67, 0, -2.02]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine17.geometry}
        material={nodes.magazine17.material}
        position={[1.17, 0.48, -5.26]}
        rotation={[0, -0.44, 0]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine24.geometry}
        material={nodes.magazine24.material}
        position={[1.27, 0.84, -5.26]}
        rotation={[0, 0.26, 0]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine18.geometry}
        material={nodes.magazine18.material}
        position={[1.17, 0.47, -5.26]}
        rotation={[0, -0.44, 0]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine23.geometry}
        material={nodes.magazine23.material}
        position={[1.27, 0.83, -5.26]}
        rotation={[0, 0.26, 0]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine19.geometry}
        material={nodes.magazine19.material}
        position={[1.17, 0.49, -5.26]}
        rotation={[0, -0.44, 0]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine25.geometry}
        material={nodes.magazine25.material}
        position={[1.27, 0.85, -5.26]}
        rotation={[0, 0.26, 0]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine20.geometry}
        material={nodes.magazine20.material}
        position={[1.18, 0.46, -5.26]}
        rotation={[0, -0.44, 0]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine22.geometry}
        material={nodes.magazine22.material}
        position={[1.28, 0.82, -5.26]}
        rotation={[0, 0.26, 0]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine21.geometry}
        material={nodes.magazine21.material}
        position={[1.17, 0.5, -5.26]}
        rotation={[0, -0.44, 0]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine26.geometry}
        material={nodes.magazine26.material}
        position={[1.27, 0.86, -5.26]}
        rotation={[0, 0.26, 0]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.big_table.geometry}
        material={nodes.big_table.material}
        position={[3.93, 0.75, -2.79]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_seat_002.geometry}
        material={nodes.chair_seat_002.material}
        position={[4.68, 0.77, -2.08]}
        rotation={[Math.PI / 2, 0, -1.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_seat_001.geometry}
        material={nodes.chair_seat_001.material}
        position={[4.61, 0.77, -3.23]}
        rotation={[Math.PI / 2, 0, -Math.PI / 3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_seat.geometry}
        material={nodes.chair_seat.material}
        position={[2.89, 0.77, -3.1]}
        rotation={[Math.PI / 2, 0, 0.96]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_seat_003.geometry}
        material={nodes.chair_seat_003.material}
        position={[3, 0.77, -2.08]}
        rotation={[Math.PI / 2, 0, 1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.zhaluzi_01.geometry}
        material={nodes.zhaluzi_01.material}
        position={[5.29, 1.27, -1.99]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.zhaluzi_02.geometry}
        material={nodes.zhaluzi_02.material}
        position={[5.29, 1.27, -2.74]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.zhaluzi_03.geometry}
        material={nodes.zhaluzi_03.material}
        position={[5.29, 1.27, -3.49]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.zhaluzi_04.geometry}
        material={nodes.zhaluzi_04.material}
        position={[5.29, 1.27, -4.25]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line031.geometry}
        material={nodes.Line031.material}
        position={[4.47, 0.4, -0.34]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line032.geometry}
        material={nodes.Line032.material}
        position={[-0.81, 0.78, -0.67]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line033.geometry}
        material={nodes.Line033.material}
        position={[-4.38, 0.78, -0.59]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pen005.geometry}
        material={nodes.pen005.material}
        position={[-2.58, 0.79, -3.4]}
        rotation={[-Math.PI, 0.7, -Math.PI]}
        scale={79.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pen006.geometry}
        material={nodes.pen006.material}
        position={[-3.4, 0.79, -5.16]}
        rotation={[0, Math.PI / 3, 0]}
        scale={79.38}
      />
      <skinnedMesh
        geometry={nodes.Box072.geometry}
        material={nodes.Box072.material}
        skeleton={nodes.Box072.skeleton}
        position={[-1.91, 0, -9.84]}
        rotation={[Math.PI, -0.2, Math.PI]}
      />
      <skinnedMesh
        geometry={nodes.Box073.geometry}
        material={nodes.Box073.material}
        skeleton={nodes.Box073.skeleton}
        position={[2.75, -0.19, -0.55]}
        rotation={[0, 0.04, 0]}
      />
      <skinnedMesh
        geometry={nodes.Box074.geometry}
        material={nodes.Box074.material}
        skeleton={nodes.Box074.skeleton}
        position={[0.75, 0, -2.19]}
        rotation={[Math.PI, -0.2, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/sasamba.gltf");
